//CREATE A TWEET
###
DELETE http://localhost:9000/api/followers/6363454ed67bf46fbf2bcbce/63634563d67bf46fbf2bcbd0 HTTP/1.1
Content-Type: application/json

//GET ALL USERS
###
GET http://localhost:9000/api/tweets HTTP/1.1
Content-Type: application/json

//GET LIKE
###
DELETE http://localhost:9000/api/likes/6363454ed67bf46fbf2bcbce/636346f21bc3cfafc6f36640 HTTP/1.1
Content-Type: application/json

{
    "user":"6363454ed67bf46fbf2bcbce",
    "tweet":"636346f21bc3cfafc6f36640"
    }


